name: nrandom
description: Random index in array
version: 1.0.0
homepage: https://github.com/nhancv/nrandom

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
